# Generated by Django 4.2.7 on 2026-03-07 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='公司名称')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('scale', models.CharField(choices=[('small', '小型（1-50人）'), ('medium', '中型（51-500人）'), ('large', '大型（501-2000人）'), ('enterprise', '企业级（2000人以上）')], max_length=20, verbose_name='公司规模')),
                ('nature', models.CharField(choices=[('private', '民营企业'), ('state', '国有企业'), ('foreign', '外资企业'), ('joint', '合资企业'), ('startup', '创业公司')], max_length=20, verbose_name='企业性质')),
                ('ranking', models.CharField(choices=[('red', '红榜'), ('normal', '普通'), ('black', '黑榜')], default='normal', max_length=10, verbose_name='红黑榜')),
                ('avg_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='平均薪资')),
                ('description', models.TextField(verbose_name='公司描述')),
                ('warning_info', models.TextField(blank=True, verbose_name='警告信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '企业信息',
                'verbose_name_plural': '企业信息',
                'ordering': ['-ranking', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='职位名称')),
                ('salary_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低薪资')),
                ('salary_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最高薪资')),
                ('requirements', models.TextField(verbose_name='职位要求')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company_reviews.company', verbose_name='公司')),
            ],
            options={
                'verbose_name': '职位信息',
                'verbose_name_plural': '职位信息',
            },
        ),
    ]
