# Generated by Django 4.2.7 on 2026-03-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='职位名称')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('salary_range', models.CharField(blank=True, max_length=255, null=True, verbose_name='薪资范围')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司名称')),
                ('industry', models.CharField(blank=True, max_length=255, null=True, verbose_name='行业')),
                ('company_scale', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司规模')),
                ('company_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司类型')),
                ('job_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='职位代码')),
                ('job_details', models.TextField(blank=True, null=True, verbose_name='职位详情')),
                ('update_date', models.DateTimeField(blank=True, null=True, verbose_name='更新日期')),
                ('company_details', models.TextField(blank=True, null=True, verbose_name='公司详情')),
                ('job_source_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='职位来源URL')),
            ],
            options={
                'verbose_name': '公司职位信息',
                'verbose_name_plural': '公司职位信息',
                'db_table': 'company_info',
                'managed': False,
            },
        ),
    ]
