# Generated by Django 4.2.7 on 2026-03-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_reviews", "0002_companyinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobFair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "university",
                    models.CharField(
                        choices=[
                            ("hnu", "湖南大学"),
                            ("csust", "长沙理工大学"),
                            ("hnust", "湖南科技大学"),
                            ("hnu_science", "湖南师范大学"),
                            ("csu", "中南大学"),
                            ("csuft", "中南林业科技大学"),
                            ("hnuc", "湖南城市学院"),
                            ("hnctu", "湖南工业大学"),
                            ("hunnu", "湖南农业大学"),
                            ("hust", "湖南理工学院"),
                            ("hnu_medicine", "湖南医药学院"),
                            ("hnvtc", "湖南铁道职业技术学院"),
                            ("other", "其他高校"),
                        ],
                        max_length=50,
                        verbose_name="高校名称",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="双选会名称")),
                ("date", models.DateTimeField(verbose_name="举办时间")),
                ("location", models.CharField(max_length=255, verbose_name="举办地点")),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="联系电话"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="联系邮箱"),
                ),
                ("description", models.TextField(verbose_name="双选会详情")),
                (
                    "registration_link",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="报名链接"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "湖南高校双选会",
                "verbose_name_plural": "湖南高校双选会",
                "ordering": ["-date"],
            },
        ),
        migrations.AlterModelTable(
            name="companyinfo",
            table="company_info_backup",
        ),
    ]
