# Generated by Django 4.2.7 on 2026-03-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_reviews", "0003_jobfair_alter_companyinfo_table"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobfair",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "湖南高校双选会",
                "verbose_name_plural": "湖南高校双选会",
            },
        ),
        migrations.AlterField(
            model_name="jobfair",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="联系邮箱"
            ),
        ),
        migrations.AlterField(
            model_name="jobfair",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="联系电话"
            ),
        ),
        migrations.AlterField(
            model_name="jobfair",
            name="date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="举办时间"),
        ),
        migrations.AlterField(
            model_name="jobfair",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="双选会详情"),
        ),
        migrations.AlterField(
            model_name="jobfair",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="举办地点"
            ),
        ),
        migrations.AlterField(
            model_name="jobfair",
            name="registration_link",
            field=models.CharField(blank=True, max_length=500, verbose_name="网站链接"),
        ),
    ]
