# Generated by Django 4.2.7 on 2026-03-31 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "company_reviews",
            "0004_alter_jobfair_options_alter_jobfair_contact_email_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobfair",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="jobfair",
            name="contact_phone",
        ),
        migrations.RemoveField(
            model_name="jobfair",
            name="date",
        ),
        migrations.RemoveField(
            model_name="jobfair",
            name="description",
        ),
        migrations.RemoveField(
            model_name="jobfair",
            name="location",
        ),
    ]
