# Generated by Django 4.2.7 on 2026-03-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_reviews", "0005_remove_jobfair_contact_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobfair",
            options={
                "ordering": ["-date"],
                "verbose_name": "湖南高校双选会",
                "verbose_name_plural": "湖南高校双选会",
            },
        ),
        migrations.AddField(
            model_name="jobfair",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="联系邮箱"
            ),
        ),
        migrations.AddField(
            model_name="jobfair",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="联系电话"
            ),
        ),
        migrations.AddField(
            model_name="jobfair",
            name="date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="举办时间"),
        ),
        migrations.AddField(
            model_name="jobfair",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="双选会详情"),
        ),
        migrations.AddField(
            model_name="jobfair",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="举办地点"
            ),
        ),
        migrations.AlterField(
            model_name="jobfair",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="双选会名称"
            ),
        ),
        migrations.AlterField(
            model_name="jobfair",
            name="registration_link",
            field=models.CharField(blank=True, max_length=500, verbose_name="报名链接"),
        ),
        migrations.AlterField(
            model_name="jobfair",
            name="university",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hnu", "湖南大学"),
                    ("csust", "长沙理工大学"),
                    ("hnust", "湖南科技大学"),
                    ("hnu_science", "湖南师范大学"),
                    ("csu", "中南大学"),
                    ("csuft", "中南林业科技大学"),
                    ("hnuc", "湖南城市学院"),
                    ("hnctu", "湖南工业大学"),
                    ("hunnu", "湖南农业大学"),
                    ("hust", "湖南理工学院"),
                    ("hnu_medicine", "湖南医药学院"),
                    ("hnvtc", "湖南铁道职业技术学院"),
                    ("other", "其他高校"),
                ],
                max_length=50,
                null=True,
                verbose_name="高校名称",
            ),
        ),
    ]
