# Generated by Django 4.2.7 on 2026-04-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "company_reviews",
            "0006_alter_jobfair_options_jobfair_contact_email_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="jobfair",
            name="university_url",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="高校就业网站链接"
            ),
        ),
    ]
