# Generated by Django 4.2.7 on 2026-04-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_reviews", "0008_alter_jobfair_university"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobfair",
            name="university",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hnu", "湖南大学"),
                    ("csust", "长沙理工大学"),
                    ("hnust", "湖南科技大学"),
                    ("hunnu_science", "湖南师范大学"),
                    ("csu", "中南大学"),
                    ("csuft", "中南林业科技大学"),
                    ("hnuc", "湖南城市学院"),
                    ("hnctu", "湖南工业大学"),
                    ("hunnu", "湖南农业大学"),
                    ("hust", "湖南理工学院"),
                    ("hnu_medicine", "湖南医药学院"),
                    ("hnvtc", "湖南铁道职业技术学院"),
                    ("xtu", "湘潭大学"),
                    ("usc", "南华大学"),
                    ("hutb", "湖南工商大学"),
                    ("jsu", "吉首大学"),
                    ("hhtc", "怀化学院"),
                    ("hnfnu", "湖南第一师范学院"),
                    ("hufe", "湖南财政经济学院"),
                    ("hnxxy", "湖南信息学院"),
                    ("hnyxy", "湖南应用技术学院"),
                    ("hnist", "湖南理工学院"),
                    ("hynu", "衡阳师范学院"),
                    ("huas", "湖南文理学院"),
                    ("hnjcxy", "湖南警察学院"),
                    ("hngxy", "湖南工学院"),
                    ("syxy", "邵阳学院"),
                    ("xnu", "湘南学院"),
                    ("hnrwkjxy", "湖南人文科技学院"),
                    ("hnjtgcxy", "湖南交通工程学院"),
                    ("hnrjzy", "湖南软件职业技术大学"),
                    ("other", "其他高校"),
                ],
                max_length=50,
                null=True,
                verbose_name="高校名称",
            ),
        ),
    ]
