CREATE TABLE IF NOT EXISTS company_reviews_company (id bigint(20) NOT NULL AUTO_INCREMENT, name varchar(100) NOT NULL, city varchar(50) NOT NULL, scale varchar(20) NOT NULL, nature varchar(20) NOT NULL, avg_salary decimal(10,2) NOT NULL, description longtext NOT NULL, warning_info longtext DEFAULT NULL, ranking varchar(10) NOT NULL, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS company_reviews_companyjob (id bigint(20) NOT NULL AUTO_INCREMENT, company_id bigint(20) NOT NULL, title varchar(100) NOT NULL, salary_min decimal(10,2) NOT NULL, salary_max decimal(10,2) NOT NULL, requirements longtext NOT NULL, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY (id), KEY company_id (company_id), CONSTRAINT company_reviews_companyjob_company_id_fk FOREIGN KEY (company_id) REFERENCES company_reviews_company (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS company_reviews_companyinfo (id bigint(20) NOT NULL AUTO_INCREMENT, name varchar(100) NOT NULL, address varchar(200) NOT NULL, company_scale varchar(50) NOT NULL, company_type varchar(50) NOT NULL, industry varchar(50) NOT NULL, description longtext NOT NULL, job_count int(11) NOT NULL DEFAULT 0, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS company_reviews_companyjobinfo (id bigint(20) NOT NULL AUTO_INCREMENT, company_info_id bigint(20) NOT NULL, job_title varchar(100) NOT NULL, salary_range varchar(50) NOT NULL, address varchar(200) NOT NULL, job_source_url varchar(200) DEFAULT NULL, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY (id), KEY company_info_id (company_info_id), CONSTRAINT company_reviews_companyjobinfo_company_info_id_fk FOREIGN KEY (company_info_id) REFERENCES company_reviews_companyinfo (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS resumes_resume (id bigint(20) NOT NULL AUTO_INCREMENT, user_id bigint(20) NOT NULL, file_path varchar(255) NOT NULL, file_name varchar(255) NOT NULL, file_size bigint(20) NOT NULL, upload_date datetime(6) NOT NULL, PRIMARY KEY (id), KEY user_id (user_id), CONSTRAINT resumes_resume_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_integration_aitag (id bigint(20) NOT NULL AUTO_INCREMENT, name varchar(50) NOT NULL, description longtext DEFAULT NULL, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY (id), UNIQUE KEY name (name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_integration_aichatpair (id bigint(20) NOT NULL AUTO_INCREMENT, conversation_id bigint(20) NOT NULL, user_input longtext NOT NULL, ai_output longtext NOT NULL, input_time datetime(6) NOT NULL, output_time datetime(6) NOT NULL, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY (id), KEY conversation_id (conversation_id), CONSTRAINT ai_integration_aichatpair_conversation_id_fk FOREIGN KEY (conversation_id) REFERENCES ai_integration_aiconversation (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_integration_careerevaluationrecord (id bigint(20) NOT NULL AUTO_INCREMENT, session_id varchar(100) NOT NULL, user_id bigint(20) DEFAULT NULL, input_data json NOT NULL, output_data json NOT NULL, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY (id), UNIQUE KEY session_id (session_id), KEY user_id (user_id), CONSTRAINT ai_integration_careerevaluationrecord_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_integration_careerplanreport (id bigint(20) NOT NULL AUTO_INCREMENT, session_id varchar(100) NOT NULL, user_id bigint(20) DEFAULT NULL, input_data json NOT NULL, output_data json NOT NULL, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY (id), UNIQUE KEY session_id (session_id), KEY user_id (user_id), CONSTRAINT ai_integration_careerplanreport_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_integration_aiusagerecord (id bigint(20) NOT NULL AUTO_INCREMENT, user_id bigint(20) DEFAULT NULL, usage_type varchar(50) NOT NULL, related_id varchar(100) DEFAULT NULL, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY (id), KEY user_id (user_id), CONSTRAINT ai_integration_aiusagerecord_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_integration_careerrecommendationrecord (id bigint(20) NOT NULL AUTO_INCREMENT, session_id varchar(100) NOT NULL, user_id bigint(20) DEFAULT NULL, input_data json NOT NULL, output_data json NOT NULL, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY (id), UNIQUE KEY session_id (session_id), KEY user_id (user_id), CONSTRAINT ai_integration_careerrecommendationrecord_user_id_fk FOREIGN KEY (user_id) REFERENCES users (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_integration_aiprompt (id bigint(20) NOT NULL AUTO_INCREMENT, prompt_type varchar(50) NOT NULL, system_prompt longtext NOT NULL, user_prompt_template longtext NOT NULL, is_active tinyint(1) NOT NULL DEFAULT 1, created_at datetime(6) NOT NULL, updated_at datetime(6) NOT NULL, PRIMARY KEY (id), UNIQUE KEY prompt_type (prompt_type)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_integration_aiconversation_tags (id bigint(20) NOT NULL AUTO_INCREMENT, aiconversation_id bigint(20) NOT NULL, aitag_id bigint(20) NOT NULL, PRIMARY KEY (id), UNIQUE KEY aiconversation_id_aitag_id (aiconversation_id,aitag_id), KEY aiconversation_id (aiconversation_id), KEY aitag_id (aitag_id), CONSTRAINT ai_integration_aiconversation_tags_aiconversation_id_fk FOREIGN KEY (aiconversation_id) REFERENCES ai_integration_aiconversation (id), CONSTRAINT ai_integration_aiconversation_tags_aitag_id_fk FOREIGN KEY (aitag_id) REFERENCES ai_integration_aitag (id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;