# Generated by Django 4.2.7 on 2026-03-17 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('mode', models.CharField(choices=[('interview', '面试模式'), ('review', '复盘模式'), ('normal', '普通模式'), ('career', '职业规划模式')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI对话会话',
                'verbose_name_plural': 'AI对话会话',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', '用户'), ('ai', 'AI')], max_length=20)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ai_integration.aiconversation')),
            ],
            options={
                'verbose_name': 'AI聊天记录',
                'verbose_name_plural': 'AI聊天记录',
                'ordering': ['timestamp'],
            },
        ),
    ]
