# Generated by Django 4.2.7 on 2026-03-17 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='标签描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'AI标签',
                'verbose_name_plural': 'AI标签',
            },
        ),
        migrations.AlterField(
            model_name='aichatlog',
            name='content',
            field=models.TextField(verbose_name='消息内容'),
        ),
        migrations.AlterField(
            model_name='aichatlog',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ai_integration.aiconversation', verbose_name='会话'),
        ),
        migrations.AlterField(
            model_name='aichatlog',
            name='message_type',
            field=models.CharField(choices=[('user', '用户'), ('ai', 'AI')], max_length=20, verbose_name='消息类型'),
        ),
        migrations.AlterField(
            model_name='aichatlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='mode',
            field=models.CharField(choices=[('interview', '面试模式'), ('review', '复盘模式'), ('normal', '普通模式'), ('career', '职业规划模式')], max_length=50, verbose_name='对话模式'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='session_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='会话ID'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='aiconversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='CareerPlanReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='报告会话ID')),
                ('report_content', models.TextField(verbose_name='报告内容')),
                ('radar_data', models.JSONField(default=dict, verbose_name='雷达图数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tags', models.ManyToManyField(blank=True, related_name='plan_reports', to='ai_integration.aitag', verbose_name='标签')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '职业生涯规划报告',
                'verbose_name_plural': '职业生涯规划报告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerEvaluationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='评测会话ID')),
                ('selected_careers', models.JSONField(default=list, verbose_name='选择的职业')),
                ('evaluation_result', models.JSONField(default=dict, verbose_name='评测结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tags', models.ManyToManyField(blank=True, related_name='evaluation_records', to='ai_integration.aitag', verbose_name='标签')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '职业评测记录',
                'verbose_name_plural': '职业评测记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIUsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('chat', '聊天对话'), ('evaluation', '职业评测'), ('plan', '职业规划报告')], max_length=50, verbose_name='使用类型')),
                ('related_id', models.CharField(max_length=100, verbose_name='关联ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tags', models.ManyToManyField(blank=True, related_name='usage_records', to='ai_integration.aitag', verbose_name='标签')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI使用记录',
                'verbose_name_plural': 'AI使用记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='conversations', to='ai_integration.aitag', verbose_name='标签'),
        ),
    ]
