# Generated by Django 4.2.7 on 2026-03-17 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_integration', '0002_aitag_alter_aichatlog_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagerecord',
            name='usage_type',
            field=models.CharField(choices=[('chat', '聊天对话'), ('evaluation', '职业评测'), ('plan', '职业规划报告'), ('recommendation', '职业推荐')], max_length=50, verbose_name='使用类型'),
        ),
        migrations.CreateModel(
            name='CareerRecommendationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='推荐会话ID')),
                ('self_introduction', models.TextField(verbose_name='自我介绍内容')),
                ('recommendations', models.JSONField(default=list, verbose_name='推荐结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tags', models.ManyToManyField(blank=True, related_name='recommendation_records', to='ai_integration.aitag', verbose_name='标签')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '职业推荐记录',
                'verbose_name_plural': '职业推荐记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
