# Generated by Django 4.2.7 on 2026-03-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0003_alter_aiusagerecord_usage_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagerecord',
            name='usage_type',
            field=models.CharField(choices=[('chat', '聊天对话'), ('career_consultant', '职业规划咨询'), ('evaluation', '职业评测'), ('plan', '职业规划报告'), ('recommendation', '职业推荐')], max_length=50, verbose_name='使用类型'),
        ),
    ]
