# Generated by Django 4.2.7 on 2026-03-17 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0004_alter_aiusagerecord_usage_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField(verbose_name='用户输入')),
                ('ai_output', models.TextField(verbose_name='AI输出')),
                ('input_time', models.DateTimeField(auto_now_add=True, verbose_name='输入时间')),
                ('output_time', models.DateTimeField(blank=True, null=True, verbose_name='输出时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='ai_integration.aiconversation', verbose_name='会话')),
            ],
            options={
                'verbose_name': 'AI聊天问答对',
                'verbose_name_plural': 'AI聊天问答对',
                'ordering': ['input_time'],
            },
        ),
    ]
