# Generated by Django 4.2.7 on 2026-03-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0005_aichatpair'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIChatLog',
        ),
    ]
