# Generated by Django 4.2.7 on 2026-03-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0006_delete_aichatlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('chat', '闲聊模式'), ('interview', '面试模式'), ('career', '职业规划模式'), ('recommendation', '职业推荐模式')], max_length=50, unique=True, verbose_name='提示词类型')),
                ('system_prompt', models.TextField(verbose_name='系统提示词')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI提示词配置',
                'verbose_name_plural': 'AI提示词配置',
                'ordering': ['prompt_type'],
            },
        ),
    ]
