# Generated by Django 4.2.7 on 2026-03-18 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ai_integration', '0007_aiprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconversation',
            name='context_aware',
            field=models.BooleanField(default=True, verbose_name='是否上下文感知'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='short_term_memory_size',
            field=models.IntegerField(default=10, verbose_name='短期记忆大小'),
        ),
        migrations.CreateModel(
            name='LongTermMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='记忆键')),
                ('value', models.TextField(verbose_name='记忆值')),
                ('category', models.CharField(choices=[('career_goal', '职业目标'), ('skills', '技能特长'), ('interview_feedback', '面试反馈'), ('preferences', '重要偏好'), ('other', '其他')], max_length=50, verbose_name='记忆类别')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='long_term_memories', to='ai_integration.aiconversation', verbose_name='关联会话')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '长期记忆',
                'verbose_name_plural': '长期记忆',
                'ordering': ['-updated_at'],
            },
        ),
    ]
