# Generated by Django 4.2.7 on 2026-03-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_integration", "0008_aiconversation_context_aware_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="careerrecommendationrecord",
            name="tags",
        ),
        migrations.AddField(
            model_name="aiprompt",
            name="user_prompt_template",
            field=models.TextField(
                blank=True, null=True, verbose_name="用户提示词模板"
            ),
        ),
    ]
