# Generated by Django 4.2.7 on 2026-03-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_integration", "0010_careerrecommendationrecord_analysis_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="careerrecommendationrecord",
            name="introduction_preview",
            field=models.TextField(blank=True, verbose_name="自我介绍预览（高亮部分）"),
        ),
    ]
