# Generated by Django 4.2.7 on 2026-04-09 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_integration", "0011_careerrecommendationrecord_introduction_preview"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeniorAdvice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255, verbose_name="公司名称")),
                ("position", models.CharField(max_length=255, verbose_name="职位名称")),
                (
                    "senior_name",
                    models.CharField(max_length=100, verbose_name="学长/学姐姓名"),
                ),
                (
                    "graduation_year",
                    models.CharField(max_length=4, verbose_name="毕业年份"),
                ),
                (
                    "current_company",
                    models.CharField(max_length=255, verbose_name="当前公司"),
                ),
                ("advice", models.TextField(verbose_name="详细建议")),
                (
                    "salary_info",
                    models.CharField(max_length=100, verbose_name="薪资信息"),
                ),
                ("pros", models.JSONField(default=list, verbose_name="优点")),
                ("cons", models.JSONField(default=list, verbose_name="缺点")),
                ("rating", models.FloatField(max_length=5.0, verbose_name="评分")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="是否审核通过"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "学长学姐建议",
                "verbose_name_plural": "学长学姐建议",
                "ordering": ["-created_at"],
            },
        ),
    ]
