# Generated by Django 4.2.7 on 2026-04-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_integration", "0012_senioradvice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiprompt",
            name="prompt_type",
            field=models.CharField(
                choices=[
                    ("chat", "闲聊模式"),
                    ("interview", "面试模式"),
                    ("career", "职业规划模式"),
                    ("recommendation", "职业推荐模式"),
                    ("resume", "简历模式"),
                ],
                max_length=50,
                unique=True,
                verbose_name="提示词类型",
            ),
        ),
    ]
