# Generated by Django 4.2.7 on 2026-04-26 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_integration", "0013_alter_aiprompt_prompt_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewReviewRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interview_style",
                    models.CharField(
                        choices=[
                            ("gentle", "温和面"),
                            ("technical", "技术面"),
                            ("pressure", "压力面"),
                            ("behavioral", "行为面"),
                        ],
                        max_length=50,
                        verbose_name="面试风格",
                    ),
                ),
                (
                    "interview_duration",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="面试时长(分钟)"
                    ),
                ),
                ("review_content", models.TextField(verbose_name="复盘报告内容")),
                (
                    "strengths",
                    models.TextField(blank=True, null=True, verbose_name="优点总结"),
                ),
                (
                    "weaknesses",
                    models.TextField(blank=True, null=True, verbose_name="待改进点"),
                ),
                (
                    "suggestions",
                    models.TextField(blank=True, null=True, verbose_name="改进建议"),
                ),
                (
                    "overall_score",
                    models.FloatField(blank=True, null=True, verbose_name="综合评分"),
                ),
                (
                    "communication_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="沟通表达评分"
                    ),
                ),
                (
                    "technical_score",
                    models.FloatField(
                        blank=True, null=True, verbose_name="技术能力评分"
                    ),
                ),
                (
                    "question_count",
                    models.IntegerField(default=0, verbose_name="问题数量"),
                ),
                (
                    "answer_count",
                    models.IntegerField(default=0, verbose_name="回答数量"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_records",
                        to="ai_integration.aiconversation",
                        verbose_name="关联会话",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "面试复盘记录",
                "verbose_name_plural": "面试复盘记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
