# Generated by Django 4.2.7 on 2026-03-08 03:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import resumes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=resumes.models.avatar_upload_path, verbose_name='头像')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
                'db_table': 'resumes',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='技能名称')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resumes.resume', verbose_name='简历')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='公司')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('period', models.CharField(max_length=50, verbose_name='时间段')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='resumes.resume', verbose_name='简历')),
            ],
            options={
                'verbose_name': '工作经验',
                'verbose_name_plural': '工作经验',
                'db_table': 'experience',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200, verbose_name='学校')),
                ('major', models.CharField(blank=True, max_length=100, null=True, verbose_name='专业')),
                ('period', models.CharField(max_length=50, verbose_name='时间段')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resumes.resume', verbose_name='简历')),
            ],
            options={
                'verbose_name': '教育背景',
                'verbose_name_plural': '教育背景',
                'db_table': 'education',
            },
        ),
    ]
