# Generated by Django 4.2.7 on 2026-03-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='self_introduction',
            field=models.TextField(blank=True, null=True, verbose_name='自我介绍'),
        ),
    ]
