# Generated by Django 4.2.7 on 2026-03-12 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_self_introduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='self_introduction',
        ),
    ]
