# Generated by Django 4.2.7 on 2026-03-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_self_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='self_introduction',
            field=models.TextField(blank=True, null=True, verbose_name='自我介绍'),
        ),
    ]
