# Generated by Django 4.2.7 on 2026-03-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_options_alter_user_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/%Y/%m/", verbose_name="头像"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="公司"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="current_position",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="当前职位"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="education",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="学历"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="github",
            field=models.URLField(blank=True, null=True, verbose_name="GitHub"),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin",
            field=models.URLField(blank=True, null=True, verbose_name="LinkedIn"),
        ),
        migrations.AddField(
            model_name="user",
            name="major",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="专业"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="手机号"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="school",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="学校"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.JSONField(blank=True, default=list, verbose_name="技能标签"),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="个人网站"),
        ),
        migrations.AddField(
            model_name="user",
            name="work_years",
            field=models.IntegerField(blank=True, null=True, verbose_name="工作年限"),
        ),
    ]
