# Generated by Django 4.2.7 on 2026-04-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_avatar_user_company_user_current_position_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company",
        ),
        migrations.RemoveField(
            model_name="user",
            name="current_position",
        ),
        migrations.RemoveField(
            model_name="user",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="user",
            name="skills",
        ),
        migrations.RemoveField(
            model_name="user",
            name="website",
        ),
        migrations.RemoveField(
            model_name="user",
            name="work_years",
        ),
        migrations.AlterField(
            model_name="user",
            name="self_introduction",
            field=models.TextField(blank=True, null=True, verbose_name="简介"),
        ),
    ]
