# Generated by Django 4.2.7 on 2026-04-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="地址"
            ),
        ),
    ]
