# Generated by Django 4.2.7 on 2026-04-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="性别"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="grade",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="年级"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="名字"
            ),
        ),
    ]
