# Generated by Django 4.2.7 on 2026-04-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_gender_user_grade_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="career_goal",
            field=models.TextField(blank=True, null=True, verbose_name="职业期望"),
        ),
        migrations.AddField(
            model_name="user",
            name="other_skills",
            field=models.TextField(blank=True, null=True, verbose_name="其他技能"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile",
            field=models.TextField(blank=True, null=True, verbose_name="简介"),
        ),
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.TextField(blank=True, null=True, verbose_name="技能"),
        ),
        migrations.AlterField(
            model_name="user",
            name="self_introduction",
            field=models.TextField(blank=True, null=True, verbose_name="条件自述"),
        ),
    ]
